apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prosody-data
  annotations:
    nfs.io/storage-path: prosody-data
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
