kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: prosody
  labels:
    app: prosody 
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.244
  selector:
    app: prosody
  ports:
  - port: 5000
    name: proxy65
  - port: 5222
    name: c2s
  - port: 5223
    name: c2s-legacy
  - port: 5269
    name: xmpp
  - port: 5280
    name: bosh
  - port: 5281
    name: bosh-secure
